log:
  dev: false

database:
  uri: mongodb://app:3XKaEgtpUmh553MEm8UQvScc23w9u73Q@localhost:27017/art-of-metrics

# Simply for refernce
mongodb:
  admin:
    username: admin
    password: QYfdEBQF2rFsRH9FAF2DrwQ4wU5X9NY9
    db: admin
    roles:
      - userAdminAnyDatabase
      - readWriteAnyDatabase
      - clusterAdmin
  app:
    username: app
    password: 3XKaEgtpUmh553MEm8UQvScc23w9u73Q
    db: aom
    roles:
      - dbAdmin
      - readWrite

stripe:
  secret: sk_test_P84JOD8KzBkCfpTOxoq83dKo
  apiVersion: !!str 2016-03-07
